INSERT INTO phrase_history_en (phrase) VALUES ('"The Lord is my strength and my shield; in him my heart trusts, and I am helped." - Psalm 28:7');
INSERT INTO phrase_history_en (phrase) VALUES ('"I have come that they may have life, and that they may have it more abundantly." - John 10:10');
INSERT INTO phrase_history_en (phrase) VALUES ('"Seek the Lord while he may be found; call upon him while he is near." - Isaiah 55:6');
INSERT INTO phrase_history_en (phrase) VALUES ('"Indeed, we are the temple of the living God." - 2 Corinthians 6:16');
INSERT INTO phrase_history_en (phrase) VALUES ('"Commit your work to the Lord, and your plans will be established." - Proverbs 16:3');
INSERT INTO phrase_history_en (phrase) VALUES ('"Fulfill your vows to the Lord your God, and let all the neighboring lands bring gifts to the One to be feared." - Psalm 76:11');
INSERT INTO phrase_history_en (phrase) VALUES ('"Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles." - Hebrews 12:1');
INSERT INTO phrase_history_en (phrase) VALUES ('"Trust in the Lord with all your heart and lean not on your own understanding." - Proverbs 3:5');
INSERT INTO phrase_history_en (phrase) VALUES ('"Those who wait for the Lord shall renew their strength" - Isaiah 40:31');
INSERT INTO phrase_history_en (phrase) VALUES ('"Cast all your anxiety on him because he cares for you." - 1 Peter 5:7');
INSERT INTO phrase_history_en (phrase) VALUES ('"Rejoice in the Lord always; again I will say, Rejoice." - Philippians 4:4');
INSERT INTO phrase_history_en (phrase) VALUES ('"My soul glorifies the Lord and my spirit rejoices in God my Savior." - Luke 1:46-47');
INSERT INTO phrase_history_en (phrase) VALUES ('"Blessed are the peacemakers, for they will be called children of God." - Matthew 5:9');
INSERT INTO phrase_history_en (phrase) VALUES ('"Thou shalt not be afraid for the terror by night; nor for the arrow that flieth by day." - Psalm 91:5');
INSERT INTO phrase_history_en (phrase) VALUES ('"Be strong and take heart, all you who hope in the Lord." - Psalm 31:24');
INSERT INTO phrase_history_en (phrase) VALUES ('"Brothers and sisters, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead." - Philippians 3:13');
INSERT INTO phrase_history_en (phrase) VALUES ('"Keep your lives free from the love of money and be content with what you have, because God has said, ''Never will I leave you; never will I forsake you.''" - Hebrews 13:5');
INSERT INTO phrase_history_en (phrase) VALUES ('"Teach us to number our days, that we may gain a heart of wisdom." - Psalm 90:12');
INSERT INTO phrase_history_en (phrase) VALUES ('"Draw near to God, and He will draw near to you." - James 4:8');
INSERT INTO phrase_history_en (phrase) VALUES ('"Take heart; it is I. Do not be afraid." - Mark 6:50');
INSERT INTO phrase_history_en (phrase) VALUES ('"Fear not, for I have redeemed you; I have called you by name, you are mine." - Isaiah 43:1');
INSERT INTO phrase_history_en (phrase) VALUES ('"Do not worry about your life, what you will eat or drink; or about your body, what you will wear. Is not life more than food, and the body more than clothes?" - Matthew 6:25');
INSERT INTO phrase_history_en (phrase) VALUES ('"Commit your way to the Lord; trust in Him and He will do this." - Psalm 37:5');
INSERT INTO phrase_history_en (phrase) VALUES ('"Do not be afraid; just believe." - Mark 5:36');
INSERT INTO phrase_history_en (phrase) VALUES ('"Be strong and of good courage, fear not, nor be afraid of them: for the Lord thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee." - Deuteronomy 31:6');
INSERT INTO phrase_history_en (phrase) VALUES ('"Her children rise up and call her blessed." - Proverbs 31:28');
INSERT INTO phrase_history_en (phrase) VALUES ('"Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you." - Matthew 7:7');
INSERT INTO phrase_history_en (phrase) VALUES ('"Let us fix our eyes on Jesus, the author and perfecter of our faith." - Hebrews 12:2');
INSERT INTO phrase_history_en (phrase) VALUES ('"The earth is the Lord''s, and everything in it." - Psalm 24:1');
INSERT INTO phrase_history_en (phrase) VALUES ('"Be strong and courageous, do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go." - Joshua 1:9');
INSERT INTO phrase_history_en (phrase) VALUES ('"Let your light shine before others, that they may see your good deeds and glorify your Father in heaven." - Matthew 5:16"');
INSERT INTO phrase_history_en (phrase) VALUES ('"For I know the plans I have for you," declares the LORD, "plans to prosper you and not to harm you, plans to give you hope and a future." - Jeremiah 29:11');
INSERT INTO phrase_history_en (phrase) VALUES ('"I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life." - Jesus: John 8:12"');
INSERT INTO phrase_history_en (phrase) VALUES ('"Her spirit rejoices in God my Savior," - Luke 1:47');
INSERT INTO phrase_history_en (phrase) VALUES ('"Strengthen the weary hands, and support the feeble knees." - Isaiah 35:3');
INSERT INTO phrase_history_en (phrase) VALUES ('"Behold, I am doing a new thing; now it springs forth, do you not perceive it?" - Isaiah 43:19');
INSERT INTO phrase_history_en (phrase) VALUES ('"May the God of hope fill you with all joy and peace in believing, so that by the power of the Holy Spirit you may abound in hope." - Romans 15:13');
INSERT INTO phrase_history_en (phrase) VALUES ('"How good and pleasant it is when God’s people live together in unity!" - Psalm 133:1');
INSERT INTO phrase_history_en (phrase) VALUES ('"Love one another. As I have loved you, so you must love one another." - John 13:34');
INSERT INTO phrase_history_en (phrase) VALUES ('"His mercy extends to those who fear him, from generation to generation." - Luke 1:50');
INSERT INTO phrase_history_en (phrase) VALUES ('"Be still, and know that I am God." - Psalm 46:10');
INSERT INTO phrase_history_en (phrase) VALUES ('"Strengthen the weary and revive the brokenhearted." - Isaiah 61:1');
INSERT INTO phrase_history_en (phrase) VALUES ('"Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls." - Matthew 11:29');
INSERT INTO phrase_history_en (phrase) VALUES ('"Those who sow with tears will reap with songs of joy." - Psalm 126:5');
INSERT INTO phrase_history_en (phrase) VALUES ('"Thus says the Lord: Stand by the roads, and look, and ask for the ancient paths, where the good way is; and walk in it, and find rest for your souls." - Jeremiah 6:16');
INSERT INTO phrase_history_en (phrase) VALUES ('"Behold, the virgin shall conceive and bear a son, and they shall call his name Immanuel" - Isaiah 7:14');
INSERT INTO phrase_history_en (phrase) VALUES ('"How beautiful upon the mountains are the feet of him who brings good news, who publishes peace, who brings good news of happiness, who publishes salvation, who says to Zion, ''Your God reigns!''" - Isaiah 52:7');
INSERT INTO phrase_history_en (phrase) VALUES ('"Even though I walk through the darkest valley, I fear no evil; for you are with me." - Psalm 23:4');
INSERT INTO phrase_history_en (phrase) VALUES ('"Therefore, my beloved, as you have always obeyed, not only in my presence but now much more in my absence, work out your own salvation with fear and trembling." - Philippians 2:12');
INSERT INTO phrase_history_en (phrase) VALUES ('"Look at the birds of the air; they do not sow or reap or store away in barns, and yet your heavenly Father feeds them. Are you not much more valuable than they?" - Matthew 6:26');
INSERT INTO phrase_history_en (phrase) VALUES ('"Let us hold unswervingly to the hope we profess, for he who promised is faithful." - Hebrews 10:23');
INSERT INTO phrase_history_en (phrase) VALUES ('"Sing to the Lord a new song; sing to the Lord, all the earth." - Psalm 96:1');
INSERT INTO phrase_history_en (phrase) VALUES ('"Sing and rejoice, O daughter of Zion!" - Zechariah 2:10');
INSERT INTO phrase_history_en (phrase) VALUES ('"I am the bread of life; whoever comes to me will never go hungry, and whoever believes in me will never be thirsty." - John 6:35');
INSERT INTO phrase_history_en (phrase) VALUES ('"Let my prayer rise before you as incense, the lifting up of my hands as the evening sacrifice!" - Psalm 141:2');
INSERT INTO phrase_history_en (phrase) VALUES ('"Let everything that has breath praise the Lord!" - Psalm 150:6');
INSERT INTO phrase_history_en (phrase) VALUES ('"Therefore encourage one another and build each other up, just as in fact you are doing." - 1 Thessalonians 5:11');
INSERT INTO phrase_history_en (phrase) VALUES ('"I am the good shepherd. The good shepherd lays down his life for the sheep." - John 10:11');
INSERT INTO phrase_history_en (phrase) VALUES ('"Even to your old age and gray hairs I am he, I am he who will sustain you. I have made you and I will carry you; I will sustain you and I will rescue you." - Isaiah 46:4');
INSERT INTO phrase_history_en (phrase) VALUES ('"Give us this day our daily bread." - Matthew 6:11');
INSERT INTO phrase_history_en (phrase) VALUES ('"Fear not, for I am with you; be not dismayed, for I am your God." - Isaiah 41:10');
INSERT INTO phrase_history_en (phrase) VALUES ('"Those who cling to worthless idols turn away from God''s love for them." - Jonah 2:8');
INSERT INTO phrase_history_en (phrase) VALUES ('"Great is the mystery of godliness: God was manifested in the flesh, justified in the Spirit, seen by angels, preached among the nations, believed on in the world, received up in glory." - 1 Timothy 3:16');
INSERT INTO phrase_history_en (phrase) VALUES ('"Behold, I am the handmaid of the Lord; let it be to me according to your word." - Luke 1:38');
INSERT INTO phrase_history_en (phrase) VALUES ('"Commit your way to the Lord; trust in him and he will do this." - Psalm 37:5');
INSERT INTO phrase_history_en (phrase) VALUES ('"Rejoice always, pray without ceasing, give thanks in all circumstances." - 1 Thessalonians 5:16-18');
INSERT INTO phrase_history_en (phrase) VALUES ('"Jesus said to her, ''I am the resurrection and the life. The one who believes in me will live, even though they die;''" - John 11:25');
INSERT INTO phrase_history_en (phrase) VALUES ('"Rejoice in hope, be patient in tribulation, be constant in prayer." - Romans 12:12');
INSERT INTO phrase_history_en (phrase) VALUES ('"His mercies are new every morning." - Lamentations 3:23');
INSERT INTO phrase_history_en (phrase) VALUES ('"He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God." - Micah 6:8');
INSERT INTO phrase_history_en (phrase) VALUES ('"The Lord is near to the brokenhearted and saves the crushed in spirit." - Psalm 34:18');
INSERT INTO phrase_history_en (phrase) VALUES ('"Behold, I stand at the door and knock." - Revelation 3:20');
INSERT INTO phrase_history_en (phrase) VALUES ('"Let all that you do be done in love." - 1 Corinthians 16:14');
INSERT INTO phrase_history_en (phrase) VALUES ('"Your word is a lamp to my feet and a light for my path." - Psalm 119:105');
INSERT INTO phrase_history_en (phrase) VALUES ('"Even youths grow tired and weary, and young men stumble and fall; but those who hope in the Lord will renew their strength." - Isaiah 40:30-31');
INSERT INTO phrase_history_en (phrase) VALUES ('"I can do all things through Christ who strengthens me." - Philippians 4:13');
INSERT INTO phrase_history_en (phrase) VALUES ('"I will restore to you the years that the swarming locust has eaten." - Joel 2:25');
INSERT INTO phrase_history_en (phrase) VALUES ('"Surely I am with you always, to the very end of the age." - Matthew 28:20');
INSERT INTO phrase_history_en (phrase) VALUES ('"Behold, I am the light of the world. Whoever follows me will not walk in darkness, but will have the light of life." - John 8:12');
INSERT INTO phrase_history_en (phrase) VALUES ('"Jesus looked at them and said, ''With man this is impossible, but with God all things are possible.''" - Matthew 19:26');
INSERT INTO phrase_history_en (phrase) VALUES ('"Put on the whole armor of God, that you may be able to stand against the schemes of the devil." - Ephesians 6:11');
INSERT INTO phrase_history_en (phrase) VALUES ('"I know that my redeemer lives." - Job 19:25');
INSERT INTO phrase_history_en (phrase) VALUES ('"Therefore, go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit," - Matthew 28:19');
INSERT INTO phrase_history_en (phrase) VALUES ('"Be strong and courageous, for you shall cause this people to inherit the land that I swore to their fathers to give them." - Joshua 1:6');
INSERT INTO phrase_history_en (phrase) VALUES ('"Elijah went up to heaven in a whirlwind." - 2 Kings 2:11');
INSERT INTO phrase_history_en (phrase) VALUES ('"Magnificat anima mea Dominum" - Luke 1:46');
INSERT INTO phrase_history_en (phrase) VALUES ('"She will give birth to a son, and you are to give him the name Jesus, because he will save his people from their sins." - Matthew 1:21');
INSERT INTO phrase_history_en (phrase) VALUES ('"Behold, the handmaid of the Lord; be it unto me according to thy word." - Luke 1:38');
INSERT INTO phrase_history_en (phrase) VALUES ('"Cast all your anxiety on him because he cares for you." - Peter 5:7');
INSERT INTO phrase_history_en (phrase) VALUES ('"Do not be afraid; you are of more value than many sparrows." - Matthew 10:31');
INSERT INTO phrase_history_en (phrase) VALUES ('"With God all things are possible." - Matthew 19:26');
INSERT INTO phrase_history_en (phrase) VALUES ('"Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God." - Philippians 4:6');
INSERT INTO phrase_history_en (phrase) VALUES ('"Consider the lilies of the field, how they grow; they neither toil nor spin, yet I tell you, even Solomon in all his glory was not arrayed like one of these." - Matthew 6:28-29');
INSERT INTO phrase_history_en (phrase) VALUES ('"Therefore take up the whole armor of God, that you may be able to withstand in the evil day, and having done all, to stand firm." - Ephesians 6:13');
INSERT INTO phrase_history_en (phrase) VALUES ('"He has sent me to bind up the brokenhearted, to proclaim freedom for the captives and release from darkness for the prisoners" - Isaiah 61:1');
INSERT INTO phrase_history_en (phrase) VALUES ('"Let us love one another, for love is from God; and everyone who loves is born of God and knows God." - 1 John 4:7');
INSERT INTO phrase_history_en (phrase) VALUES ('"Therefore encourage one another and build each other up." - 1 Thessalonians 5:11');
INSERT INTO phrase_history_en (phrase) VALUES ('"Sing joyfully to the Lord, you righteous; it is fitting for the upright to praise him." - Psalm 33:1');
INSERT INTO phrase_history_en (phrase) VALUES ('"Therefore do not worry about tomorrow, for tomorrow will worry about itself." - Matthew 6:34');
INSERT INTO phrase_history_en (phrase) VALUES ('"Therefore, we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day." - 2 Corinthians 4:16');
INSERT INTO phrase_history_en (phrase) VALUES ('"Now faith is the assurance of things hoped for, the conviction of things not seen." - Hebrews 11:1');
INSERT INTO phrase_history_en (phrase) VALUES ('"Be thou my vision, O Lord of my heart" - Unknown: Irish Hymn');
INSERT INTO phrase_history_en (phrase) VALUES ('"Be strong and courageous, for you are the one who will lead these people to possess all the land I swore to their ancestors I would give them." - Joshua 1:6');
INSERT INTO phrase_history_en (phrase) VALUES ('"Therefore encourage one another and build each other up, just as in fact you are doing." - 1 Thessalonians 5:11"');
INSERT INTO phrase_history_en (phrase) VALUES ('"Strengthen your brothers." - Luke 22:32');
INSERT INTO phrase_history_en (phrase) VALUES ('"Let us run with perseverance the race marked out for us, fixing our eyes on Jesus." - Hebrews 12:1-2');
INSERT INTO phrase_history_en (phrase) VALUES ('"Jesus called them to him and said, ''You know that the rulers of the Gentiles lord it over them...''" - Matthew 20:25');
INSERT INTO phrase_history_en (phrase) VALUES ('"Peace I leave with you; my peace I give to you." - John 14:27');
INSERT INTO phrase_history_en (phrase) VALUES ('"Do not be afraid, little flock, for your Father has been pleased to give you the kingdom." - Luke 12:32');
INSERT INTO phrase_history_en (phrase) VALUES ('"I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you." - Psalm 32:8');
INSERT INTO phrase_history_en (phrase) VALUES ('"Listen, you who are far away, what I have done; and you who are near, acknowledge my might!" - Isaiah 33:13');
INSERT INTO phrase_history_en (phrase) VALUES ('"Evening, morning, and at noon I cry out in distress, and he hears my voice." - Psalm 55:17');
INSERT INTO phrase_history_en (phrase) VALUES ('"Each of you should use whatever gift you have received to serve others, as faithful stewards of God’s grace in its various forms." - Peter 4:10');
INSERT INTO phrase_history_en (phrase) VALUES ('"Delight yourself in the Lord, and he will give you the desires of your heart." - Psalm 37:4');
INSERT INTO phrase_history_en (phrase) VALUES ('"Your word is a lamp to my feet and a light to my path." - Psalm 119:105');
INSERT INTO phrase_history_en (phrase) VALUES ('"Indeed, the very hairs of your head are all numbered. Fear not therefore: ye are of more value than many sparrows." - Luke 12:7');
INSERT INTO phrase_history_en (phrase) VALUES ('"He gives power to the faint, and to him who has no might he increases strength." - Isaiah 40:29');
INSERT INTO phrase_history_en (phrase) VALUES ('"God is our refuge and strength, a very present help in trouble." - Psalm 46:1');
INSERT INTO phrase_history_en (phrase) VALUES ('"Yet I will rejoice in the Lord; I will take joy in the God of my salvation." - Habakkuk 3:18');
INSERT INTO phrase_history_en (phrase) VALUES ('"He has filled the hungry with good things, and the rich he has sent away empty." - Luke 1:53');
INSERT INTO phrase_history_en (phrase) VALUES ('"Do not be afraid; for behold, I bring you good tidings of great joy which will be to all people." - Luke 2:10');
INSERT INTO phrase_history_en (phrase) VALUES ('"Let your roots grow down into Him, and let your lives be built on Him." - Colossians 2:7');
INSERT INTO phrase_history_en (phrase) VALUES ('"Rejoice with those who rejoice; mourn with those who mourn." - Romans 12:15');
INSERT INTO phrase_history_en (phrase) VALUES ('"Look to the Lord and his strength; seek his face always." - 1 Chronicles 16:11');
INSERT INTO phrase_history_en (phrase) VALUES ('"Do not be afraid, Mary; you have found favor with God." - Luke 1:30');
INSERT INTO phrase_history_en (phrase) VALUES ('"The Lord is my shepherd; I shall not want." - Psalm 23:1');
INSERT INTO phrase_history_en (phrase) VALUES ('"Every good gift and every perfect gift is from above, coming down from the Father of lights." - James 1:17');
INSERT INTO phrase_history_en (phrase) VALUES ('"Indeed, I will not forsake you." - Hebrews 13:5');
INSERT INTO phrase_history_en (phrase) VALUES ('"Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come." - 2 Corinthians 5:17');
INSERT INTO phrase_history_en (phrase) VALUES ('"Be steadfast, immovable, always abounding in the work of the Lord" - 1 Corinthians 15:58');
INSERT INTO phrase_history_en (phrase) VALUES ('"Mary said, ''My soul magnifies the Lord, and my spirit rejoices in God my Savior.''" - Luke 1:46-47');
INSERT INTO phrase_history_en (phrase) VALUES ('"Jesus Christ is the same yesterday and today and forever." - Hebrews 13:8');
