INSERT INTO phrase_history_es (phrase) VALUES ('El Señor es mi fuerza y ​​mi escudo; en él confía mi corazón, y soy socorrido. - Salmo 28:7');
INSERT INTO phrase_history_es (phrase) VALUES ('He venido para que tengan vida, y para que la tengan en abundancia. - Juan 10:10');
INSERT INTO phrase_history_es (phrase) VALUES ('Buscad al Señor mientras puede ser hallado; llamadle mientras está cercano. - Isaías 55:6');
INSERT INTO phrase_history_es (phrase) VALUES ('He aquí, somos el templo del Dios viviente. - 2 Corintios 6:16');
INSERT INTO phrase_history_es (phrase) VALUES ('Encomienda tu obra al Señor, y tus planes se cumplirán. - Proverbios 16:3');
INSERT INTO phrase_history_es (phrase) VALUES ('Cumple tus votos al Señor tu Dios, y que todas las tierras vecinas traigan ofrendas al Temible. - Salmo 76:11');
INSERT INTO phrase_history_es (phrase) VALUES ('Por tanto, ya que estamos rodeados por una gran nube de testigos, despojémonos de todo lo que nos estorba y del pecado que tan fácilmente nos asedia. - Hebreos 12:1');
INSERT INTO phrase_history_es (phrase) VALUES ('"Confía en el Señor con todo tu corazón y no te apoyes en tu propia prudencia." - Proverbios 3:5');
INSERT INTO phrase_history_es (phrase) VALUES ('"Los que esperan en el Señor renovarán sus fuerzas." - Isaías 40:31');
INSERT INTO phrase_history_es (phrase) VALUES ('"Echa toda tu ansiedad sobre él, porque él cuida de ti." - 1 Pedro 5:7');
INSERT INTO phrase_history_es (phrase) VALUES ('"Regocijaos en el Señor siempre; otra vez os digo: ¡Regocijaos!" - Filipenses 4:4');
INSERT INTO phrase_history_es (phrase) VALUES ('"Mi alma glorifica al Señor y mi espíritu se regocija en Dios mi Salvador." - Lucas 1:46-47');
INSERT INTO phrase_history_es (phrase) VALUES ('"Bienaventurados los pacificadores, porque ellos serán llamados hijos de Dios." - Mateo 5:9');
INSERT INTO phrase_history_es (phrase) VALUES ('"No temerás el terror nocturno, ni la saeta que vuela de día." - Salmo 91:5');
INSERT INTO phrase_history_es (phrase) VALUES ('"Sean fuertes y tengan ánimo todos los que esperan en el Señor." - Salmo 31:24');
INSERT INTO phrase_history_es (phrase) VALUES ('"Hermanos, no considero haberlo ya alcanzado. Pero una cosa hago: olvidando ciertamente lo que queda atrás y extendiéndome a lo que está delante." - Filipenses 3:13');
INSERT INTO phrase_history_es (phrase) VALUES ('"Mantengan su vida libre del amor al dinero y estén contentos con lo que tienen, porque Dios ha dicho: ''Nunca te dejaré, nunca te desampararé''." - Hebreos 13:5');
INSERT INTO phrase_history_es (phrase) VALUES ('"Enséñanos a contar bien nuestros días, para que nuestro corazón adquiera sabiduría." - Salmo 90:12');
INSERT INTO phrase_history_es (phrase) VALUES ('"Acérquense a Dios, y él se acercará a ustedes." - Santiago 4:8');
INSERT INTO phrase_history_es (phrase) VALUES ('"¡Ánimo! Soy yo. No tengan miedo." - Marcos 6:50');
INSERT INTO phrase_history_es (phrase) VALUES ('"No temas, porque yo te he redimido; te he llamado por tu nombre; eres mío." - Isaías 43:1');
INSERT INTO phrase_history_es (phrase) VALUES ('"No te preocupes por tu vida, qué comerás o beberás; ni por tu cuerpo, qué vestirás. ¿No es la vida más que el alimento, y el cuerpo más que la ropa?" - Mateo 6:25');
INSERT INTO phrase_history_es (phrase) VALUES ('"Encomienda tu camino al Señor; confía en Él, y Él lo hará." - Salmo 37:5');
INSERT INTO phrase_history_es (phrase) VALUES ('"No temas; solo cree." - Marcos 5:36');
INSERT INTO phrase_history_es (phrase) VALUES ('"Esfuérzate y sé valiente; no temas ni tengas miedo de ellos, porque el Señor tu Dios es quien va contigo; no te dejará ni te desamparará." - Deuteronomio 31:6');
INSERT INTO phrase_history_es (phrase) VALUES ('"Sus hijos se levantan y la llaman bienaventurada." - Proverbios 31:28');
INSERT INTO phrase_history_es (phrase) VALUES ('"Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá." - Mateo 7:7');
INSERT INTO phrase_history_es (phrase) VALUES ('"Fijemos la mirada en Jesús, el autor y consumador de nuestra fe." - Hebreos 12:2');
INSERT INTO phrase_history_es (phrase) VALUES ('"Del Señor es la tierra y todo lo que hay en ella." - Salmo 24:1');
INSERT INTO phrase_history_es (phrase) VALUES ('"Sé fuerte y valiente; no temas ni desanimes, porque el Señor tu Dios estará contigo dondequiera que vayas." - Josué 1:9');
INSERT INTO phrase_history_es (phrase) VALUES ('"Deja que tu luz brille delante de los hombres, para que vean tus buenas obras y glorifiquen a tu Padre que está en los cielos." - Mateo 5:16');
INSERT INTO phrase_history_es (phrase) VALUES ('"Porque yo sé los planes que tengo para vosotros -declara el Señor-, planes de bienestar y no de calamidad, para daros un futuro y una esperanza." - Jeremías 29:11');
INSERT INTO phrase_history_es (phrase) VALUES ('"Yo soy la luz del mundo." El que me sigue no andará en tinieblas, sino que tendrá la luz de la vida. - Jesús: Juan 8:12');
INSERT INTO phrase_history_es (phrase) VALUES ('"Su espíritu se regocija en Dios mi Salvador." - Lucas 1:47');
INSERT INTO phrase_history_es (phrase) VALUES ('"Fortaleced las manos cansadas y sostened las rodillas debilitadas." - Isaías 35:3');
INSERT INTO phrase_history_es (phrase) VALUES ('"Mirad, hago algo nuevo; ya está brotando, ¿no lo percibís?" - Isaías 43:19');
INSERT INTO phrase_history_es (phrase) VALUES ('"Que el Dios de la esperanza os llene de todo gozo y paz en el creer, para que por el poder del Espíritu Santo abundéis en esperanza." - Romanos 15:13');
INSERT INTO phrase_history_es (phrase) VALUES ('"¡Cuán bueno y placentero es cuando el pueblo de Dios vive unido!" - Salmo 133:1');
INSERT INTO phrase_history_es (phrase) VALUES ('"Ámense los unos a los otros. Como yo os he amado, también debéis amaros los unos a los otros." - Juan 13:34');
INSERT INTO phrase_history_es (phrase) VALUES ('"Su misericordia se extiende a los que le temen, de generación en generación." - Lucas 1:50');
INSERT INTO phrase_history_es (phrase) VALUES ('"Estad quietos, y sabed que yo soy Dios." - Salmo 46:10');
INSERT INTO phrase_history_es (phrase) VALUES ('"Fortaleced al cansado, y reanimad al quebrantado de corazón." - Isaías 61:1');
INSERT INTO phrase_history_es (phrase) VALUES ('"Llevad mi yugo sobre vosotros y aprended de mí, que soy manso y humilde de corazón, y hallaréis descanso para vuestras almas." - Mateo 11:29');
INSERT INTO phrase_history_es (phrase) VALUES ('"Los que siembran con lágrimas, con cánticos de alegría segarán." - Salmo 126:5');
INSERT INTO phrase_history_es (phrase) VALUES ('"Así dice el Señor: Paraos junto a los caminos, y mirad, y preguntad por las sendas antiguas, cuál es el buen camino; y andad por él, y hallaréis descanso para vuestras almas." - Jeremías 6:16');
INSERT INTO phrase_history_es (phrase) VALUES ('"He aquí que la virgen concebirá y dará a luz un hijo, y le pondrás por nombre Emanuel." - Isaías 7:14');
INSERT INTO phrase_history_es (phrase) VALUES ('"¡Cuán hermosos son sobre los montes los pies del que trae buenas nuevas, del que anuncia la paz, del que trae buenas nuevas de felicidad, del que anuncia la salvación, del que dice a Sión: "¡Tu Dios reina!"" - Isaías 52:7');
INSERT INTO phrase_history_es (phrase) VALUES ('"Aunque ande por el valle más oscuro, no temeré mal alguno, porque tú estás conmigo." - Salmo 23:4');
INSERT INTO phrase_history_es (phrase) VALUES ('"Por tanto, amados míos, como siempre habéis obedecido, no solo en mi presencia, sino mucho más ahora en mi ausencia, ocupaos en vuestra salvación con temor y temblor." - Filipenses 2:12');
INSERT INTO phrase_history_es (phrase) VALUES ('"Mirad las aves del cielo: no siembran, ni siegan, ni almacenan en graneros, y sin embargo, vuestro Padre celestial las alimenta. ¿No sois vosotros mucho más valiosos que ellas?" - Mateo 6:26');
INSERT INTO phrase_history_es (phrase) VALUES ('Mantengámonos firmes en la esperanza que profesamos, porque fiel es el que prometió. - Hebreos 10:23');
INSERT INTO phrase_history_es (phrase) VALUES ('¡Cantad al Señor un cántico nuevo; cantad al Señor, toda la tierra! - Salmo 96:1');
INSERT INTO phrase_history_es (phrase) VALUES ('¡Canta y alégrate, hija de Sión! - Zacarías 2:10');
INSERT INTO phrase_history_es (phrase) VALUES ('Yo soy el pan de vida; el que a mí viene nunca tendrá hambre, y el que en mí cree nunca tendrá sed. - Juan 6:35');
INSERT INTO phrase_history_es (phrase) VALUES ('¡Que mi oración suba ante ti como incienso, el alzar de mis manos como la ofrenda de la tarde! - Salmo 141:2');
INSERT INTO phrase_history_es (phrase) VALUES ('¡Todo lo que respira alabe al Señor! - Salmo 150:6');
INSERT INTO phrase_history_es (phrase) VALUES ('Por tanto, anímense y edifíquense unos a otros, tal como lo hacen. - 1 Tesalonicenses 5:11');
INSERT INTO phrase_history_es (phrase) VALUES ('Yo soy el buen pastor. El buen pastor da su vida por las ovejas. - Juan 10:11');
INSERT INTO phrase_history_es (phrase) VALUES ('"Aun en tu vejez y tus canas, yo soy quien te sustentará. Yo te hice y yo te sustentaré; yo te sustentaré y yo te rescataré." - Isaías 46:4');
INSERT INTO phrase_history_es (phrase) VALUES ('"Danos hoy nuestro pan de cada día." - Mateo 6:11');
INSERT INTO phrase_history_es (phrase) VALUES ('"No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios." - Isaías 41:10');
INSERT INTO phrase_history_es (phrase) VALUES ('"Quienes se aferran a ídolos vanos se apartan del amor de Dios por ellos." - Jonás 2:8');
INSERT INTO phrase_history_es (phrase) VALUES ('"Grande es el misterio de la piedad: Dios fue manifestado en carne, justificado en el Espíritu, visto por ángeles, predicado entre las naciones, creído en el mundo, recibido arriba en gloria." - 1 Timoteo 3:16');
INSERT INTO phrase_history_es (phrase) VALUES ('"He aquí la esclava del Señor; hágase en mí conforme a tu palabra." - Lucas 1:38');
INSERT INTO phrase_history_es (phrase) VALUES ('"Encomienda tu camino al Señor; confía en él, y él lo hará." - Salmo 37:5');
INSERT INTO phrase_history_es (phrase) VALUES ('"Regocíjense siempre, oren sin cesar, den gracias en toda circunstancia." - 1 Tesalonicenses 5:16-18');
INSERT INTO phrase_history_es (phrase) VALUES ('"Jesús le dijo: ''Yo soy la resurrección y la vida; el que cree en mí, aunque muera, vivirá;''" - Juan 11:25');
INSERT INTO phrase_history_es (phrase) VALUES ('"Regocíjense en la esperanza, sean pacientes en la tribulación, sean constantes en la oración." - Romanos 12:12');
INSERT INTO phrase_history_es (phrase) VALUES ('"Sus misericordias son nuevas cada mañana." - Lamentaciones 3:23');
INSERT INTO phrase_history_es (phrase) VALUES ('"Él te ha mostrado, oh mortal, lo que es bueno. ¿Y qué exige el Señor de ti? Actuar con justicia, amar la misericordia y humillarte ante tu Dios." - Miqueas 6:8');
INSERT INTO phrase_history_es (phrase) VALUES ('"El Señor está cerca de los quebrantados de corazón y salva a los abatidos de espíritu." - Salmo 34:18');
INSERT INTO phrase_history_es (phrase) VALUES ('"He aquí, yo estoy a la puerta y llamo." - Apocalipsis 3:20');
INSERT INTO phrase_history_es (phrase) VALUES ('"Que todo lo que hagan sea hecho con amor." - 1 Corintios 16:14');
INSERT INTO phrase_history_es (phrase) VALUES ('"Tu palabra es una lámpara a mis pies y una luz en mi camino." - Salmo 119:105');
INSERT INTO phrase_history_es (phrase) VALUES ('Incluso los jóvenes se cansan y se fatigan, y los jóvenes tropiezan y caen; pero los que esperan en el Señor renovarán sus fuerzas. - Isaías 40:30-31');
INSERT INTO phrase_history_es (phrase) VALUES ('"Todo lo puedo en Cristo que me fortalece." - Filipenses 4:13');
INSERT INTO phrase_history_es (phrase) VALUES ('"Les restituiré los años que comió la langosta." - Joel 2:25');
INSERT INTO phrase_history_es (phrase) VALUES ('"Ciertamente estoy con ustedes siempre, hasta el fin del mundo." - Mateo 28:20');
INSERT INTO phrase_history_es (phrase) VALUES ('"He aquí, yo soy la luz del mundo. El que me sigue no andará en tinieblas, sino que tendrá la luz de la vida." - Juan 8:12');
INSERT INTO phrase_history_es (phrase) VALUES ('"Jesús los miró y dijo: ''Para los hombres esto es imposible, pero para Dios todo es posible.''" - Mateo 19:26');
INSERT INTO phrase_history_es (phrase) VALUES ('"Pónganse toda la armadura de Dios, para que puedan estar firmes contra las asechanzas del diablo." - Efesios 6:11');
INSERT INTO phrase_history_es (phrase) VALUES ('"Yo sé que mi Redentor vive." - Job 19:25');
INSERT INTO phrase_history_es (phrase) VALUES ('"Por tanto, id y haced discípulos a todas las naciones, bautizándolos en el nombre del Padre, del Hijo y del Espíritu Santo." - Mateo 28:19');
INSERT INTO phrase_history_es (phrase) VALUES ('"Sed fuertes y valientes, porque haréis que este pueblo herede la tierra que juré a sus padres que les daría." - Josué 1:6');
INSERT INTO phrase_history_es (phrase) VALUES ('"Elías subió al cielo en un torbellino." - 2 Reyes 2:11');
INSERT INTO phrase_history_es (phrase) VALUES ('"Magnificat anima mea Dominum." - Lucas 1:46');
INSERT INTO phrase_history_es (phrase) VALUES ('"Dará a luz un hijo, y le pondrás por nombre Jesús, porque él salvará a su pueblo de sus pecados." - Mateo 1:21');
INSERT INTO phrase_history_es (phrase) VALUES ('"He aquí la sierva del Señor; hágase en mí conforme a tu palabra." - Lucas 1:38');
INSERT INTO phrase_history_es (phrase) VALUES ('"Echad toda vuestra ansiedad sobre él, porque él cuida de vosotros." - Pedro 5:7');
INSERT INTO phrase_history_es (phrase) VALUES ('"No tengáis miedo; vosotros valéis más que muchos gorriones." - Mateo 10:31');
INSERT INTO phrase_history_es (phrase) VALUES ('"Con Dios todo es posible." - Mateo 19:26');
INSERT INTO phrase_history_es (phrase) VALUES ('"No se inquieten por nada; más bien, en toda situación, con oración y ruego, y acción de gracias, presenten sus peticiones a Dios." - Filipenses 4:6');
INSERT INTO phrase_history_es (phrase) VALUES ('"Consideren los lirios del campo, cómo crecen; no trabajan ni hilan; sin embargo, les digo que ni siquiera Salomón en toda su gloria se vistió como uno de ellos." - Mateo 6:28-29');
INSERT INTO phrase_history_es (phrase) VALUES ('"Por tanto, tomen toda la armadura de Dios, para que puedan resistir en el día malo, y habiendo acabado todo, mantenerse firmes." - Efesios 6:13');
INSERT INTO phrase_history_es (phrase) VALUES ('"Me ha enviado a sanar a los quebrantados de corazón, a proclamar libertad a los cautivos y liberación de las tinieblas a los prisioneros." - Isaías 61:1');
INSERT INTO phrase_history_es (phrase) VALUES ('"Amémonos unos a otros, porque el amor es de Dios; y todo el que ama es nacido de Dios y conoce a Dios." - 1 Juan 4:7');
INSERT INTO phrase_history_es (phrase) VALUES ('"Por lo tanto, anímense y edifíquense unos a otros." - 1 Tesalonicenses 5:11');
INSERT INTO phrase_history_es (phrase) VALUES ('"Cantad con alegría al Señor, vosotros los justos; es propio de los rectos alabarle." - Salmo 33:1');
INSERT INTO phrase_history_es (phrase) VALUES ('"Así que, no os preocupéis por el mañana, porque el mañana traerá sus propios afanes." - Mateo 6:34');
INSERT INTO phrase_history_es (phrase) VALUES ('"Por tanto, no desmayamos. Aunque por fuera nos vamos desgastando, por dentro nos renovamos día a día." - 2 Corintios 4:16');
INSERT INTO phrase_history_es (phrase) VALUES ('"Ahora bien, la fe es la certeza de lo que se espera, la convicción de lo que no se ve." - Hebreos 11:1');
INSERT INTO phrase_history_es (phrase) VALUES ('"Sé mi visión, oh Señor de mi corazón." - Desconocido: Himno Irlandés');
INSERT INTO phrase_history_es (phrase) VALUES ('"Sé fuerte y valiente, porque tú eres quien guiará a este pueblo a poseer toda la tierra que juré a sus antepasados ​​que les daría." - Josué 1:6');
INSERT INTO phrase_history_es (phrase) VALUES ('"Por tanto, anímense y edifíquense unos a otros, tal como de hecho lo están haciendo." - 1 Tesalonicenses 5:11');
INSERT INTO phrase_history_es (phrase) VALUES ('"Fortalezcan a sus hermanos." - Lucas 22:32');
INSERT INTO phrase_history_es (phrase) VALUES ('"Corramos con perseverancia la carrera que tenemos por delante, puestos los ojos en Jesús." - Hebreos 12:1-2');
INSERT INTO phrase_history_es (phrase) VALUES ('"Jesús los llamó y les dijo: ''Ustedes saben que los gobernantes de las naciones se enseñorean de ellas...''" - Mateo 20:25');
INSERT INTO phrase_history_es (phrase) VALUES ('"La paz les dejo; Mi paz les doy." - Juan 14:27');
INSERT INTO phrase_history_es (phrase) VALUES ('"No teman, rebaño pequeño, porque a su Padre le ha placido darles el reino." - Lucas 12:32');
INSERT INTO phrase_history_es (phrase) VALUES ('"Yo los instruiré y les enseñaré el camino que deben seguir; los aconsejaré con mi mirada amorosa puesta en ustedes." - Salmo 32:8');
INSERT INTO phrase_history_es (phrase) VALUES ('"Escuchen, ustedes que están lejos, lo que he hecho; ¡Y ustedes que están cerca, reconozcan mi poder! - Isaías 33:13');
INSERT INTO phrase_history_es (phrase) VALUES ('"Tarde, mañana y mediodía clamo angustiado, y él escucha mi voz." - Salmo 55:17');
INSERT INTO phrase_history_es (phrase) VALUES ('"Cada uno de ustedes debe usar el don que ha recibido para servir a los demás, como fieles administradores de la gracia de Dios en sus diversas formas." - Pedro 4:10');
INSERT INTO phrase_history_es (phrase) VALUES ('"Deléitate en el Señor, y él te concederá las peticiones de tu corazón." - Salmo 37:4');
INSERT INTO phrase_history_es (phrase) VALUES ('"Tu palabra es una lámpara a mis pies y una luz a mi camino." - Salmo 119:105');
INSERT INTO phrase_history_es (phrase) VALUES ('"En verdad, hasta los cabellos de tu cabeza están contados. Así que no temáis; vosotros valéis más que muchos gorriones. - Lucas 12:7');
INSERT INTO phrase_history_es (phrase) VALUES ('"Él da esfuerzo al cansado, y al que no tiene ningunas, multiplica las fuerzas." - Isaías 40:29');
INSERT INTO phrase_history_es (phrase) VALUES ('"Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en los momentos difíciles." - Salmo 46:1');
INSERT INTO phrase_history_es (phrase) VALUES ('"Sin embargo, yo me alegraré en el Señor; me gozaré en el Dios de mi salvación." - Habacuc 3:18');
INSERT INTO phrase_history_es (phrase) VALUES ('"A los hambrientos los colmó de bienes, y a los ricos los despidió con las manos vacías." - Lucas 1:53');
INSERT INTO phrase_history_es (phrase) VALUES ('"No temáis; porque he aquí, os traigo buenas nuevas de gran gozo que serán para todo el pueblo." - Lucas 2:10');
INSERT INTO phrase_history_es (phrase) VALUES ('"Echen raíces en Él, y edifiquen sus vidas sobre Él." - Colosenses 2:7');
INSERT INTO phrase_history_es (phrase) VALUES ('"Alégrense con los que se alegran; lloren con los que lloran." - Romanos 12:15');
INSERT INTO phrase_history_es (phrase) VALUES ('"Confíen en el Señor y en su poder; Buscad siempre su rostro." - 1 Crónicas 16:11');
INSERT INTO phrase_history_es (phrase) VALUES ('"No temas, María; has hallado favor delante de Dios." - Lucas 1:30');
INSERT INTO phrase_history_es (phrase) VALUES ('"El Señor es mi pastor; nada me faltará." - Salmo 23:1');
INSERT INTO phrase_history_es (phrase) VALUES ('"Toda buena dádiva y todo don perfecto desciende de lo alto, del Padre de las luces." - Santiago 1:17');
INSERT INTO phrase_history_es (phrase) VALUES ('"De cierto, no te abandonaré." - Hebreos 13:5');
INSERT INTO phrase_history_es (phrase) VALUES ('"Por lo tanto, si alguno está en Cristo, es una nueva creación. Lo viejo ha pasado; He aquí, lo nuevo ha llegado." - 2 Corintios 5:17');
INSERT INTO phrase_history_es (phrase) VALUES ('"Sean firmes, constantes, abundando siempre en la obra del Señor." - 1 Corintios 15:58');
INSERT INTO phrase_history_es (phrase) VALUES ('"María dijo: ''Mi alma engrandece al Señor, y mi espíritu se regocija en Dios mi Salvador''." - Lucas 1:46-47');
INSERT INTO phrase_history_es (phrase) VALUES ('"Jesucristo es el mismo ayer, hoy y por los siglos." - Hebreos 13:8');
